name: AI Stock Analysis

on:
  schedule:
    - cron: "0 * * * 1-5"  # Runs at the top of every hour (Monday-Friday)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run AI Stock Analysis
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python AiAnalysis.py
