name: Stock Analysis Automation

on:
  schedule:
    - cron: "0 6 * * 1-5"
    - cron: "0 7 * * 1-5"
    - cron: "0 8 * * 1-5"
    - cron: "0 9 * * 1-5"
    - cron: "0 10 * * 1-5"
    - cron: "0 11 * * 1-5"
    - cron: "0 12 * * 1-5"
    - cron: "0 13 * * 1-5"
    - cron: "0 14 * * 1-5"
    - cron: "0 15 * * 1-5"
    - cron: "0 16 * * 1-5"
    - cron: "0 17 * * 1-5"
    - cron: "0 18 * * 1-5"
    - cron: "0 19 * * 1-5"
    - cron: "0 20 * * 1-5"
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_stock_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set Up Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_1 }}" | jq . > creds1.json
          echo "${{ secrets.GOOGLE_CREDENTIALS_2 }}" | jq . > creds2.json

      - name: Run FetchData Script
        run: python fetchData.py

      - name: Run ScoreUpdate Script
        run: python scoreUpdate.py

      - name: Run UpdateHybrid Script
        run: python updateHybrid.py

      - name: Run UpdateTop Script
        run: python updateTop.py
