name: Stock Analysis Automation

on:
  schedule:
    - cron: "0 11,13,15,17,19,21,23 * * 1-5"  # Runs at the start of every hour from 6 AM - 8 PM (Monday-Friday)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-stock-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches latest code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Adjust if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Up Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_1 }}" > creds1.json
          echo "${{ secrets.GOOGLE_CREDENTIALS_2 }}" > creds2.json
          sed -i 's/\\n/\n/g' creds1.json
          sed -i 's/\\n/\n/g' creds2.json

      - name: Run Fetch Data Script
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
        run: python fetchData.py

      - name: Run Score Update Script
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
        run: python scoreUpdate.py

      - name: Run Update Hybrid Script
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
        run: python updateHybrid.py

      - name: Run Update Top Script
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
        run: python updateTop.py
      - name: Run Update earning Script
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
        run: python updateEarnings.py
      - name: Run SP trend Script
        env:
          GOOGLE_CREDENTIALS_1: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
          GOOGLE_CREDENTIALS_2: ${{ secrets.GOOGLE_CREDENTIALS_2 }}
        run: python spTrend.py
