- name: Set Up Google Credentials
  run: |
    echo "${{ secrets.GOOGLE_CREDENTIALS_1 }}" > creds1.json
    echo "${{ secrets.GOOGLE_CREDENTIALS_2 }}" > creds2.json
  on:
  schedule:
    - cron: "*/5 6-20 * * 1-5"  # Runs every hour from 6 AM to 8 PM (Monday-Friday)
  workflow_dispatch:  # Allows manual trigger



